# Input PDF
pdf: PN3_GLOBAL_NNPDF31_nnlo_as_0118_070219-001

# GAN setup
g_nodes  : 512
d_nodes  : 1024
g_act    : leakyrelu
d_act    : leakyrelu

# Optimizer setup
d_opt    : adam
gan_opt  : adam
epochs   : 100

# Intermediate steps to train the Critic & Generator
nd_steps : 5
ng_steps : 1

# Intrinsic features
add_xlayer : True
preprocessing: True
