# Choose PDF
pdf: PN3_GLOBAL_NNPDF31_nnlo_as_0118_070219-001

# Choose Grid
# Options: custom or lhapdf
x_grid   : custom

# GAN setup
hyperopt: 
    architecture  : hp.choice('architecture', ['dnn', 'dcnn'])
    g_nodes  : hp.choice('g_nodes', [128, 256, 512])
    d_nodes  : hp.choice('d_nodes', [128, 256, 512, 1024])
    g_loss   : hp.choice('g_loss', ['mean_squared_error', 'binary_crossentropy'])
    d_loss   : hp.choice('d_loss', ['mean_squared_error', 'binary_crossentropy'])
    gan_loss : hp.choice('gan_loss', ['mean_squared_error', 'binary_crossentropy'])
    g_act    : hp.choice('g_activ', ['leakyrelu', 'elu', 'relu'])
    d_act    : hp.choice('d_activ', ['leakyrelu', 'elu', 'relu'])

    # Optimizer setup
    g_opt    : hp.choice('g_opt', ['adadelta', 'sgd', 'rms'])
    d_opt    : hp.choice('d_opt', ['adadelta', 'sgd', 'rms'])
    gan_opt  : hp.choice('gan_opt', ['adadelta', 'sgd', 'rms'])
    nd_steps : hp.choice('nd_steps', [2, 3, 4, 6])
    ng_steps : hp.choice('ng_steps', [2, 3, 4, 6])

epochs   : 5000
batch_size: 64

# Intrinsic features
add_xlayer   : False
preprocessing: False
