# Lint Python Code using Super-linter
# https://github.com/github/super-linter/

name: Lint Python Code

on:
  push:
    branches-ignore: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout Code
      uses: actions/checkout@v2
    # Lint Code
    - name: Lint Code Base
      uses: docker://github/super-linter:v3
      env:
        # Only checkes the changed files
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.ACCESS_REPOS }}
