# Check the following documentation for further details
# https://github.com/codecov/codecov-action

name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Conda
      uses: goanpeca/setup-miniconda@v1
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
    - name: Install package with the dependencies
      shell: bash --login {0}
      run: |
        conda info
        python -m pip install --upgrade pip
        pip install .
        # Install LHAPDF
        conda install -y lhapdf -c https://packages.nnpdf.science/conda
    - name: Test code coverage
      shell: bash --login {0}
      run: |
        pip install .[tests]
        pytest -v --cov=./src/ganpdfs --cov-report=xml
    # - name: Upload coverage report
    #   uses: codecov/codecov-action@v1
    #   with:
    #     # Require the repository to be public
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ./coverage.xml
    #     flags: unittests
    #     name: codecov-umbrella
    #     fail_ci_if_error: true
