# Check the following documentation for further details
# https://github.com/codecov/codecov-action

name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
    - name: Install package with the dependencies
      shell: bash --login {0}
      run: |
        conda info
        # Install LHAPDF
        conda install -y lhapdf -c https://packages.nnpdf.science/conda
        # Install pdfflow from right branch for now
        pip install git+https://github.com/N3PDF/pdfflow.git@load_all_members
        # Install package
        python -m pip install --upgrade pip
        pip install .
    - name: Test code coverage
      shell: bash --login {0}
      run: |
        pip install .[tests]
        pytest -v --cov=./src/ganpdfs
